### ISSUE TITLE
If user hits back button, prompt for unsaved changes

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#399] opened 2018-08-27 22:01 UTC
If user tries to leave from problem set editing or answering a problem with unsaved work pop a modal:

You have unsaved changes, do you wish to save?

Discard Changes / Save Changes

**Comment by afijal** [comment] 2018-08-28 09:16
kind of a duplicate of #180 which I'm working on atm

**Comment by afijal** [comment] 2018-08-28 15:25
@johnhbenetech done in #180 So I believe it can be closed

**Closed** 2018-08-28 16:00 UTC
