### ISSUE TITLE
Resolve issues with UI layout on the problem set page

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#366] opened 2018-08-14 06:44 UTC
There are currently two issues with the layout of the problem set page, that are striking at the first moment of looking at this page. The first issue is duplicated scrollbar, and the second one - math area is not wrapped on the problem card. It's not a problem when the exercise is in the card title, as before, but I assume there will be many problems with longer text in the future, so we need to handle it anyway. In this case, we can't let the text escape from the card. (see screenshot)
![screenshot from 2018-08-14 08-34-34](https://user-images.githubusercontent.com/19305104/44075768-461d5c04-9f9e-11e8-8b45-715324adf322.png)

**Comment by oskarhinc** [comment] 2018-08-14 11:45
I've fixed the issue with duplicated scrollbar, but the second problem is still open. I thought about possible solutions, and none of them seem to be suitable enough. We could wrap the content like a normal text, but then there will still be a problem for bigger equations - breaking them to the new line is not a good solution. Adding scrollbar is also not the best option as it doesn't look well - in fact, both horizontal and vertical scrollbars could be required in some cases. As the home page will probably be changed soon I think spending more time on this task might be a waste, but we should think about the bigger equations in planning new home page, or when we would decide to use current problem cards. @johnhbenetech correct me if I'm wrong

**Comment by kkrawczyk123** [comment] 2018-08-14 13:29
I have also reported doubled scroll some time ago in https://github.com/benetech/MathShare/issues/347. So I will close it as well. I confirm that scroll issue has been fixed and it is not visible on all 4 browsers.

**Comment by johnhbenetech** [comment] 2018-08-14 16:03
@oskarhinc As a temporary fix could you have the problem text truncate after some # of characters and put an ellipsis.

So in the example above:

"Sarah works at a coffee shop. Her..."

**Comment by afijal** [comment] 2018-08-14 16:27
I will reopen this as one of the issues still remains

**Comment by afijal** [comment] 2018-08-24 15:39
@oskarhinc While doing other task, I've encountered some issues with this change. e.g. when latex equation is longer than 40 characters it gets truncated and doesn't display properly, please fix it.
To reproduce - add a ton of fractions stacked

**Comment by oskarhinc** [comment] 2018-08-27 06:58
Thanks, @afijal, you're right. I've fixed it, and now the text is truncated for each fraction floor: 

![screenshot from 2018-08-27 08-57-14](https://user-images.githubusercontent.com/19305104/44645263-54c41700-a9d7-11e8-8105-9e116b99effa.png)

**Comment by kkrawczyk123** [comment] 2018-08-27 14:44
Looks like the issue has been fixed right now: 
![screenshot from 2018-08-27 16-43-44](https://user-images.githubusercontent.com/33342488/44666323-6974cf00-aa18-11e8-82f9-a98deab70ac3.png)

**Closed** 2018-09-17 12:26 UTC
Labels: bug
