### ISSUE TITLE
introduce additional symbols for other math disciplines

### ISSUE THREAD

**Issue by sueannma** [benetech/MathShare#125] opened 2018-06-02 16:08 UTC
added symbols for: pre-algebra, algebra 2, trigonometry, pre-calc, calc, linear algebra 

refer to shared [Google doc](https://docs.google.com/document/d/1tjSv-vTxP9e_P3YV8mN6iE8d3iFatHK2dV-avS24brw/edit) for the additional items to be added

**Comment by NSoiffer** [comment] 2018-06-26 04:19
Duplicate of #124

**Closed by NSoiffer** 2018-06-26 04:19 UTC
Labels: UI/UX question, priority

**Comment by sueannma** [comment] 2018-06-26 10:30
@NSoiffer - reopened with some additional questions highlighted. I also tried to add the rankings of symbols by math discipline on the far right, per the operator frequency paper you previously shared with me. I'm not sure how we will use the ranking yet, but my gut tells me that might be important later. If you have an updated document that you were using (esp. since I didn't see any ranks for geometry), please feel free to pass that my way.
- yellow highlights = questions for Neil
- blue highlights = notes about AsciiMath shortcut keys
