### ISSUE TITLE
math code displaying issue

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1182] opened 2020-05-06 14:59 UTC
from teacher christina.irvine@guhsdaz.org on 5-4-20.
same teacher that reported issue #1174 
Other students faced what you see in the attached picture. In fact, my original copy for 13.1 now includes similar text:

(3x^{2.}-4x+1)+(-\mleft.x..^{2.}+x-9)

**Comment by benetechMatt** [comment] 2020-05-06 15:00
screenshot from teacher
![Screenshot from teacher showing the problem set page with all math equations being displayed as latex or mathml](https://user-images.githubusercontent.com/49413678/81192839-4ede5180-8f80-11ea-914d-16bbe500640a.jpg)

**Comment by johnhbenetech** [comment] 2020-05-06 15:17
I believe this is due to a mathlive change. Maybe @NSoiffer or @arnog has thoughts. 

@benetechMatt It would be interesting to know how the teacher created these prompts. Specifically if they copied them from elsewhere and pasted them into mathshare.

Looking at the MathLive changelog it appears they changed somethings around LaTeX formatting related to mleft and mright:
https://github.com/arnog/mathlive/blob/master/CHANGELOG.md#034-feb-5-2020

**Comment by benetechMatt** [comment] 2020-05-06 16:47
@johnhbenetech emailed the teacher to find out how she created the equations

**Comment by arnog** [comment] 2020-05-06 17:05
Which version of MathLive are you using? 

What is the input to MathLive?

Entering "(3x^{2.}-4x+1)+(-\mleft.x..^{2.}+x-9)" into the current version of MathLive (see https://mathlive.io/examples/basic/index.esm.html) renders it correctly...

**Comment by johnhbenetech** [comment] 2020-05-06 17:12
Thanks @arnog . I believe @NSoiffer pulled an update on Mar 10, so I'm assuming that's v0.34

@rupeshparab can you confirm? We can pull the latest version in dev and see if that fixes it and if not debug on our rendering side

**Comment by rupeshparab** [comment] 2020-05-06 17:22
@johnhbenetech 
I wasn't able to find the version in Neil's update commit: https://github.com/benetech/MathShare/commit/4e119d494f777738381e54d93b9215599f10aa99#diff-93477d415673af2f373e6445ec791019R1

But I tried creating a problem set with the text shared by Matt, and it seems to working on Prod and QA

https://mathshare.benetech.org/#/app/problemSet/edit/AHBCYUGKATWJY
https://mathshare-qa.diagramcenter.org/#/app/problemSet/edit/OQHXXOLDFVZP2

**Comment by johnhbenetech** [comment] 2020-05-06 17:25
@rupeshparab 

Please look at: https://mathshare.benetech.org/#/app/problemSet/solve/FBKQYW4PSPTGE

and see if anything jumps out why that would stop being rendered correctly

**Comment by rupeshparab** [comment] 2020-05-06 17:47
I tried a string from the solve link `(ab\mleft.c\mright.^{\mleft.2\mright.})(\left.\mleft.b\mright.\right.^{\mleft.3\mright.})(a)` on mathlive, it is rendering same as MathShare

MathLive:
![image](https://user-images.githubusercontent.com/6897505/81210521-9c45d780-8fef-11ea-9fb5-9b27177453ee.png)

MathShare
![image](https://user-images.githubusercontent.com/6897505/81210543-a49e1280-8fef-11ea-9d2d-7aca814ce84e.png)

I think problem might be with the text

**Comment by arnog** [comment] 2020-05-06 18:19
I think I see what's going on.

Where did this input `((ab\mleft.c\mright.^{\mleft.2\mright.})(\left.\mleft.b\mright.\right.^{\mleft.3\mright.})(a)` come from? Was it captured from a previous version of MathLive?

The problem is that MathLive doesn't handle the `\mleft` command as input, although previous version could generate is as output. I can fix this by handling it as input.

Note however that these formulas are a bit weird as they include both `\mleft.` and `\mright.` pairs, which are essentially no-op (they don't display anything but cause the content inside them to be treated as a "group" which might make the editing awkward) **and** `\left.` and `\right.` which are also no-ops (they're "invisible parentheses"). Not sure how this was input. Perhaps from one of you virtual keyboards? That might be worth addressing as well.

**Comment by arnog** [comment] 2020-05-06 18:42
OK, I've checked in a fix in MathLive master. Let me know if you need a versioned build.

**Comment by arnog** [comment] 2020-05-07 05:48
FYI, I have published Mathlive 0.50.1 which incorporates this fix.

**Comment by alexrcabral** [comment] 2020-05-08 21:15
Thanks @arnog! 

Moving forward on our side, this means we should update to the newest version of Mathlive (0.50.1) as well as conduct regression testing.

**Comment by bognasoldev89** [comment] 2020-05-26 10:50
I tried pasting problems mentioned in this issue into MathShare (qa env) and it seems to be fine now.

We'll recheck it closely during regression.

Gifs with proof:
![ms 1182](https://user-images.githubusercontent.com/51324797/82892239-6ab98f80-9f4f-11ea-88ea-e4a6e33bf1c1.gif)

![ms 1182 2](https://user-images.githubusercontent.com/51324797/82892241-6beabc80-9f4f-11ea-9b56-1d1d225e58b7.gif)

**Closed by bognasoldev89** 2020-05-26 10:50 UTC
Labels: bug

**Comment by bognasoldev89** [comment] 2020-05-27 14:11
Issue still works as expected
