### ISSUE TITLE
Sets that students previously started are displayed in their dashboard if signed in

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#977] opened 2020-02-25 19:46 UTC
Anything that a student has previously worked on when signed in will show up in their dashboard

**Comment by benetechMatt** [comment] 2020-02-29 08:03
related to #1026

**Comment by johnhbenetech** [comment] 2020-03-12 17:42
We will need mockups for how the total dashboard should look for both teachers, students, and users who are not signed in

**Comment by alexrcabral** [comment] 2020-03-24 18:00
Not fully scoped, moving back to product

**Comment by jscholes** [comment] 2020-03-24 23:59
We will await full mock-ups to review this.  But it should be flagged upfront that any additions to the dashboard need to fit into the heading hierarchy, including any new headings as necessary.  All of the best practices implemented so far for list mark-up, etc. also need to be followed.

**Comment by jscholes** [comment] 2020-03-25 00:09
Related: https://github.com/benetech/MathShare/issues/1059

**Comment by benetechMatt** [comment] 2020-03-25 21:01
**Student Dashboard:**
One section titled "Recent" where all sets the student has worked on will be displayed below the heading.
if not signed in, it asks students to sign in
Remove the "more options" menu on the right side of the set

**Teacher Dashboard:**
top section has 
"+ New Problem Set"
"Explore Problem Set Library"

"Recent" section
"Pre-Made Sets" section

**Comment by benetechMatt** [comment] 2020-03-25 21:02
#1065

**Comment by jscholes** [comment] 2020-03-25 23:40
@benetechMatt Do note the assertion from #1059 that "Recent" isn't descriptive enough.  It could apply to problems, problem sets, both, neither, or something else entirely.  Even just "Recent Sets" is better.

**Comment by rupeshparab** [comment] 2020-04-14 15:50
> **Student Dashboard:**
> One section titled "Recent" where all sets the student has worked on will be displayed below the heading.
> if not signed in, it asks students to sign in
> Remove the "more options" menu on the right side of the set
> 
> **Teacher Dashboard:**
> top section has
> "+ New Problem Set"
> "Explore Problem Set Library"
> 
> "Recent" section
> "Pre-Made Sets" section

I have a doubt, for the users logged in as students, they should not be shown the 'New Problem Set' option and 'Explore Problem Set Library' link. Recent will have the sets recently solved by the Student.
For the teacher, there would be no changes for the existing dashboard.

**Comment by rupeshparab** [comment] 2020-04-17 17:18
@benetechMatt 
Can you please confirm if these dashboard views are correct?

User who has not logged in:
![image](https://user-images.githubusercontent.com/6897505/79595999-7074b780-80fd-11ea-92a0-dfcfe58aa6d8.png)

Student:
![image](https://user-images.githubusercontent.com/6897505/79595943-5c30ba80-80fd-11ea-9bb7-f12c54863d2e.png)

Teacher:
![image](https://user-images.githubusercontent.com/6897505/79596089-939f6700-80fd-11ea-94c7-b8e8fc76add7.png)

**Comment by johnhbenetech** [comment] 2020-04-17 18:11
I will suggest some small tweaks that we will proceed with if we don't hear from product by EOD today.

1. Make sure the unauthenticated view reflects the decision in #976 
2. Capitalize the '+ Create a Problem Set' option on all views
3. Students **should** have access to the '+ Create a Problem Set' option as first option

And then I'm 90% sure this is the case already, but just to be complete: Recent Sets for students gives them the solve view, Recent Sets for teachers gives them the edit view.

**Comment by benetechMatt** [comment] 2020-04-17 18:20
In addition to John's changes in the previous comment,

Add spacing of 15px between "Recent Sets" and "Explore Problem Set Library"

Have at least 15px of spacing above and below text that is displayed under "Recent Sets". This is for "No Sets" and the sign in message.  Currently the text is too close to the heading above it and sometimes too close to the next heading of "pre-made sets"

**Comment by rupeshparab** [comment] 2020-04-21 16:08
I have addressed the feedback of above comments

User who has not logged in:
![image](https://user-images.githubusercontent.com/6897505/79887168-ed62a280-8417-11ea-80bf-d3dfdd4574af.png)

Student:
![image](https://user-images.githubusercontent.com/6897505/79887100-cdcb7a00-8417-11ea-90b4-1638d259002b.png)

Teacher:
![image](https://user-images.githubusercontent.com/6897505/79887371-49c5c200-8418-11ea-98bd-b85667eb3157.png)

No recent sets:
![image](https://user-images.githubusercontent.com/6897505/79887409-5e09bf00-8418-11ea-94e9-3008cbc2e648.png)

**Comment by rupeshparab** [comment] 2020-04-21 16:48
I have addressed the feedback of the above comments

User who has not logged in:
![image](https://user-images.githubusercontent.com/6897505/79887570-bb9e0b80-8418-11ea-9d31-c9a143b9308b.png)

Student:
![image](https://user-images.githubusercontent.com/6897505/79887646-d6708000-8418-11ea-94b7-bae48261e7f9.png)

Teacher:
![image](https://user-images.githubusercontent.com/6897505/79890982-ec347400-841d-11ea-9aeb-f8ed6aa29a27.png)


Currently it doesn't have the changes of #976 as the its branch is not yet merged

**Comment by abaranowska1** [comment] 2020-05-11 13:42
@rupeshparab 
User who has not logged in:
![All Problem Sets - Benetech Mathshare - Mozilla Firefox_247](https://user-images.githubusercontent.com/61964176/81568258-d02d4e00-939d-11ea-9700-c545f443f095.png)

Teacher:
![All Problem Sets - Benetech Mathshare - Mozilla Firefox_245](https://user-images.githubusercontent.com/61964176/81568294-db807980-939d-11ea-8219-745131ba0dd7.png)

Student:
![All Problem Sets - Benetech Mathshare - Mozilla Firefox_246](https://user-images.githubusercontent.com/61964176/81568322-e20ef100-939d-11ea-828d-49df45e6a809.png)

I see that on Student account Recent Sets are loading and loading and cannot be displayed. Could you check it ?

**Comment by rupeshparab** [comment] 2020-05-11 16:12
@johnhbenetech 
An api (https://mathshare-api-qa.diagramcenter.org/api/private/recentSolutions) which I had added in April is throwing 404 in QA env
https://github.com/benetech/MathShareBackend/commit/48dd03980a3e328ba226696a72a84be09d984771#diff-d71314653e8aa62bf2f4884066090689R44

I think it might need whitelisting in CloudFront

**Comment by johnhbenetech** [comment] 2020-05-11 16:27
@rupeshparab Is there something different about this endpoint compared to the others?

I dont remember having to whitelist /user, /config, /examplesets, etc

**Comment by rupeshparab** [comment] 2020-05-11 16:51
I thought it might be related to Cloudfront because when I enter an incorrect path (eg https://mathshare-api-qa.diagramcenter.org/api/problemSet/test) the error being thrown is different from the one which is thrown for the recentSolutions api

But it seems the 404 error is coming from the Java service, I will check its cause.

**Comment by rupeshparab** [comment] 2020-05-12 16:25
I triggered a backend deploy by pushing a random change to development, it seems it fixed the issue.
Although, I am not sure why the previous deploy was missing the api.

**Comment by abaranowska1** [comment] 2020-05-13 07:59
@rupeshparab Confirmed that Recent Sets came back on the student account 
![image](https://user-images.githubusercontent.com/61964176/81786541-1bf80880-9500-11ea-8639-aa3d3267e215.png)

**Closed** 2020-05-13 07:59 UTC
Labels: Point: 4
