### ISSUE TITLE
"Duplicate to edit/share" option changed name to "Duplicate" on the Problem Set edit page

### ISSUE THREAD

**Issue by abaranowska1** [benetech/MathShare#1256] opened 2020-06-16 09:31 UTC
**Describe the bug**
It was a ticket #1130 for changing the wording to "Duplicate to edit/share ". Now I noticed that on the Homepage it is correct 
![image](https://user-images.githubusercontent.com/61964176/84757545-92d36600-afc4-11ea-86f1-1b0b885d21c5.png),
 but on the Problem Set edit view I can see "Duplicate" 
![image](https://user-images.githubusercontent.com/61964176/84757887-02495580-afc5-11ea-8aca-47ee3236f60e.png)

**To Reproduce**
1. Go to the Problem and click 3 dot menu

**Expected behavior**
It should be "Duplicate to edit/share" instead of "Duplicate"

**Desktop :**

- QA instance
- Ubuntu 16.04 OS
- Mozilla Firefox v. 77.0.1
- Google Chrome v. 83.0.4103.61

**Comment by alexrcabral** [comment] 2020-06-16 21:46
This is intended behavior:

- On /view, the set needs to be duplicated prior to saving or sharing
- Since the /edit view is explicitly accessed the problem set owner, it does not need to be duplicated prior to share/saving

**Comment by alexrcabral** [comment] 2020-06-30 16:13
Closing the issue since this is intended behavior

**Closed by alexrcabral** 2020-06-30 16:13 UTC
Labels: bug
