### ISSUE TITLE
UI issues on setup page for a new account (Firefox and Edge)

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/MathShare#1142] opened 2020-04-20 14:17 UTC
**Describe the bug**
I noticed, that while window allowing to choose if the user is teacher or student is displayed, buttons are not aligned (on Firefox) and "Who are you?" is pushed to the left (on Edge). Chrome looks fine.

**To Reproduce**
1. Create an account
2. Sign in for the first time
3. Observe setup page

**Expected behavior**
All elements on setup page should be aligned properly and it should be applied on every major browser.

**Screenshots**
Firefox look:
![Screenshot from 2020-04-17 13-44-26](https://user-images.githubusercontent.com/51324797/79761149-5d423180-8321-11ea-8cdc-5b56898991aa.png)

Edge look:
![msedge](https://user-images.githubusercontent.com/51324797/79761182-66330300-8321-11ea-89cc-3a6e75f271ed.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4, Windows 10
 - Browser: Chrome, Firefox, Edge
 - Version: 80.0.3987.149, 75.0, 44.18362.449.0

**Comment by jscholes** [comment] 2020-04-20 18:59
Related: https://github.com/benetech/MathShare/pull/1111

**Comment by rupeshparab** [comment] 2020-04-27 19:50
@bognasoldev89 
Can this be closed as a duplicate of https://github.com/benetech/MathShare/issues/1079

**Comment by bognasoldev89** [comment] 2020-04-28 07:10
Sure!
@abaranowska1 can you confirm it's good to close and move it done if applicable?

**Comment by abaranowska1** [comment] 2020-04-28 09:51
Confirmed, this could be closed as a duplicate od #1079

**Closed by abaranowska1** 2020-04-28 09:51 UTC
Labels: bug
