### ISSUE TITLE
Investigate & Fix MathShare frontend application start

### ISSUE THREAD

**Issue by pawelcieszko** [benetech/MathShare#465] opened 2018-09-10 12:55 UTC
Due to the following changes: 
https://github.com/benetech/MathShare/commit/497d8b5f6b2731889cb8e08e2d5fc2895ea7ad9d
https://github.com/benetech/MathShare/commit/a0e044b3ba4a3c4da6ce647231d41e811ddea80d

it impossible to run MathShare frontend aplication both on Windows and Ubuntu. 

Please investigate how to fix it and **update the readme file.**

It seems there is no config package added to our repo.

**Comment by rkeiii** [comment] 2018-09-10 16:33
Hello Pawel,

I apologize for any inconvenience I may have caused with these changes. I am currently not able to reproduce the problem you describe and am wondering if you could provide a few more details.

Could you provide further details about what exactly is not working? Particularly could you provide a screenshot of the console/network tabs in Chrome developer tools when refreshing the page? Also if you're not able to compile could you paste me the JS error?

Ron

**Comment by oskarhinc** [comment] 2018-09-12 12:51
@rkeiii I guess @pawelcieszko was talking about: 

![screenshot from 2018-09-12 14-50-48](https://user-images.githubusercontent.com/19305104/45426031-4e9e8d80-b69b-11e8-9a21-26ef440c919f.png)

**Comment by oskarhinc** [comment] 2018-09-13 06:39
I've made a temporary fix for this issue (https://github.com/benetech/MathShare/commit/e6948ce8253d75b4120a2427e8db2384e3846783) however, I'm not sure if this small js configuration file is a good solution for storing the server URL and if that's what we want. Feel free to change it @rkeiii, but for now, it'll just facilitate the development.

**Comment by pawelcieszko** [comment] 2018-09-13 08:07
Hi Ron,

The screenshot attached by @oskarhinc is exactly what I meant.
Here is the Oskar's PR solving this issue:
https://github.com/benetech/MathShare/pull/485#pullrequestreview-154968686
If you have any comments/suggestions, feel free to add them.

**Comment by oskarhinc** [comment] 2018-09-17 07:31
No problem @rkeiii. I guess we can close this issue now.

**Closed by oskarhinc** 2018-09-17 07:31 UTC
