### ISSUE TITLE
Home -> Navigation -> Problem: Incorrect Role 

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/MathShare#761] opened 2019-09-09 18:33 UTC
Each problem is marked up as a button, meaning that screen reader users will expect activating them to have some sort of impact on the current page.  In fact, the content is entirely reloaded when the editor is launched, the route URL in the address bar changes, and a history entry is created by the browser. 
 
Suggested Solution 
 
Render each problem as a link instead of a button, preferably by using a < a > element directly.  Alternatively, apply a role attribute with a value of “link” to the existing < button > elements

**Comment by benetechMatt** [comment] 2019-09-20 19:23
confirmed use of role="link" in <button>

**Comment by jscholes** [comment] 2019-10-24 16:28
@rupeshparab - despite commit https://github.com/benetech/MathShare/commit/b2b1a4a3dcf0250636c17204793af7ac6934d576 referenced above, the codebase now seems to be using native `<a>` elements for these with an `href`, rather than `role="button"`.  This is an even better solution, and as such this seems to have truly been addressed in https://github.com/benetech/MathShare/commit/f4e6f2e3ca4e7613a9c5a26c58ba47b447c8831d#diff-3c8407c6c3f64ea0a3ef01ad13d9a208.

However, I have serious concerns about this block of code in https://github.com/benetech/MathShare/blob/development/src/components/Home/components/Navigation/Problem/index.js#L262:

```
const NavTag = this.props.solutions ? 'a' : 'div';
const additionalProps = {};
if (NavTag === 'a') {
	additionalProps.href = this.getLink();
} else {
	additionalProps.onClick = (e) => {
		if (this.props.addNew) {
			this.openNewProblemModal(e);
		}
	};
	additionalProps.onKeyPress = passEventForKeys(additionalProps.onClick);
}
```

If there are no problems in the list, a `<div>` will be rendered with `onClick` and `onKeyPress` handlers to allow a new one to be added.  That wouldn't be accessible to screen reader users, because it would need to be a button and as such should just be rendered as a `<button>` directly.

However, I don't understand why the responsibility of invoking the new problem modal is being placed on NavTag.  Linking to an existing problem and creating a new one are entirely different actions.

**Comment by rupeshparab** [comment] 2019-10-31 17:11
@jscholes 
The reason for having the new problem container as a div and not a button was that there is a nested button within this control.
I think that button is not really useful as clicking on the nested button or this div container both opens the new problem modal.
I think we can remove the button nested inside and change this container to a button, maybe we can keep the icon of the nested button so that there aren't any visual changes.
Only change which a user might experience is if he clicks the nested '+' icon it won't be focused as it is currently, but rather the entire container would come in focus.
Also, if we do this we won't be able to add any other button inside the 'Add New problem' container. 
@johnhbenetech will this be ok?

**Comment by johnhbenetech** [comment] 2019-10-31 17:23
I think that's fine to make the whole thing a button.

**Comment by jscholes** [comment] 2019-10-31 17:38
@johnhbenetech, @benetechMatt or @alexrcabral - I don't understand what else would go in this container?  If there will ever be multiple controls, it's obviously fine to have a `<button>` nested in a `<div>`.  But then we would need to talk about other semantics in terms of a heading for a group of controls, list mark-up, etc.

If there's only ever just going to be a single button, why is the container with text currently required?  I'm a bit confused about the design intent.  Surely you can just have a `<button>` with some text and an icon inside it.

**Comment by johnhbenetech** [comment] 2019-10-31 17:40
@jscholes You're right, I think it's an unintentional artifact. Pure button it is!

**Comment by rupeshparab** [comment] 2019-11-01 09:50
I have changed the new problem container to a button

**Comment by jscholes** [comment] 2019-11-01 13:36
Fixed in https://github.com/benetech/MathShare/commit/26733d631c232ad337c227eb181c883fc78034ae.

**Closed by jscholes** 2019-11-01 13:36 UTC
Labels: a11y
