### ISSUE TITLE
Make home page interactive

### ISSUE THREAD

**Issue by afijal** [benetech/MathShare#264] opened 2018-07-12 09:57 UTC
add onclicks and state if needed

**Comment by kkrawczyk123** [comment] 2018-07-16 12:56
On the home page there is one additional problem displayed, number 9 which is an actual duplicate of problem number 6, screenshot attached:
![screenshot from 2018-07-16 14-44-53](https://user-images.githubusercontent.com/33342488/42759405-285e5306-8907-11e8-8fac-6e10565ebf06.png)

I have noticed a weird behavior when trying to open separate problems - Other when I open it by clicking on the title and other when clicking on the rest of the problem field. Once problems are opening on title correctly and on the rest of the field white empty page is displayed with errors in console, screenshot attached:
![screenshot from 2018-07-16 14-25-01](https://user-images.githubusercontent.com/33342488/42759602-dc856f22-8907-11e8-80df-edd1dbc195a1.png)
In the other try behavior can be opposite. 
When an empty page is displayed I am unable to go back to home page with using undo browser's arrow  - still empty page is displayed so it can be connected to https://github.com/benetech/MathShare/issues/251.
All issues occur on all 4 browsers.

**Comment by afijal** [comment] 2018-07-18 12:36
@kkrawczyk123 
first issue should be fixed and the second one is related to #292

**Comment by kkrawczyk123** [comment] 2018-07-19 07:31
I confirm that the first issue has been fixed. As the second issue will be handled in https://github.com/benetech/MathShare/issues/292 so it will be tested there too.

**Closed** 2018-07-31 08:15 UTC
