### ISSUE TITLE
TTS button next to each step

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#995] opened 2020-02-27 16:56 UTC
Reads step number
Reads the equestion
Reads the explanation
Does not read edit, delete, clear all, or any other buttons

**Comment by benetechMatt** [comment] 2020-03-03 16:35
<img width="127" alt="mockup of TTS buttons.  The button is a dark gray speaker icon placed to the left of the step title.  Step 1, Step 2, and Step 3 are displayed in order.  Step 1 and step 2 have the TTS speaker button next to the step name.  Step 3 has a pause icon button because it is active." src="https://user-images.githubusercontent.com/49413678/75796846-da95f080-5d39-11ea-85b9-900881b4878d.png">

When active, the TTS button changes to a pause button. 

When there is a "clean up" row where crossed out items are removed, then only the second line with the removed elements should be read aloud.

**Comment by alexrcabral** [comment] 2020-03-24 19:57
@benetechMatt 
When resuming the speech after clicking the pause button, does it resume where it left off, or does it read from the beginning?

**Comment by alexrcabral** [comment] 2020-03-24 22:22
@benetechMatt 
Update from #1001 : Since it restarts from the beginning, it should be a stop button rather than a pause button. Pause implies that it will start speaking from where it left off.

**Comment by benetechMatt** [comment] 2020-03-26 00:55
As shown in https://github.com/benetech/MathShare/issues/1001#issuecomment-604165659. No need to update the previous mockup.
button is changed to a stop icon.
If the user stops and then plays the audio it will restart from the beginning of the section.

**Comment by bpmcneilly** [comment] 2020-03-26 21:56
For the individual step buttons, I just want to confirm that the accessible names for these icons buttons are unique for each step. 

I'll defer to @jscholes here, but my gut reaction would be to name these buttons something like "Step [number] Text to Speech", and then use an `aria-pressed` attribute to toggle the state.

**Comment by jscholes** [comment] 2020-03-26 23:10
@bpmcneilly Sounds good to me.  Maybe "Speak Step N", if we're going for an actionable theme for button text.  I like `aria-pressed`, because that update in state will be announced by a screen reader whereas a change in button text isn't guaranteed to be.

**Comment by jscholes** [comment] 2020-04-17 23:52
@benetechMatt and @alexrcabral - We've provided all accessibility comments from our side.  Any thoughts?

**Comment by alexrcabral** [comment] 2020-05-08 16:06
Thanks @jscholes and @bpmcneilly, confirming we're going with your suggestions: 
- Using the aria-pressed attribute to toggle state 
- "Speak Prompt" as the label for speaking the prompt
- "Speak Step N" as the label for each given step
- "Speak My Work" as the label for the my work section denoting the current editable step

**Comment by alexrcabral** [comment] 2020-05-14 16:23
Based on @jscholes' recommendations in #1000, rather than aria-pressed, we will move forward with explicit labels based on action:
1. "Speak Prompt" for speaking the prompt
2. "Speak Step N" for each given step
3. "Speak My Work" for the my work section denoting the current editable step

Along with the accompanying
1. "Stop Speaking Prompt"
2. "Stop Speaking Step N"
3. "Stop Speaking My Work"

**Comment by jscholes** [comment] 2020-05-14 16:42
@alexrcabral Just to highlight that this is one of those cases I referenced on the call, whereby we're copying accessibility or UX advice across tickets.  Would it make sense to have a single TTS button-related ticket which encompasses all of them?  It's okay if the answer is no, but if the tickets are significantly different, the comments probably should be as well.  I don't ever want to have outdated information be referenced, so we could even just agree to reference "source-of-truth" tickets instead of copying text.

**Comment by alexrcabral** [comment] 2020-05-15 00:28
@jscholes You're right, and this is a solid example. Since TTS and accompanying settings are already scoped/finalized with feedback and moved into dev I'd hesitate to mess with them. I'm down to reference "source-of-truth" tickets, in this case #1000. My intent with the copying over the comment was to prevent having to dig for the referenced information, since this ticket then had outdated information. 

For future issues that have been created but are still in the realm of scoping, I'll work to collapse them down to more meaningful chunks so there's less duplication of efforts.

**Comment by rupeshparab** [comment] 2020-06-02 18:05
> Based on @jscholes' recommendations in #1000, rather than aria-pressed, we will move forward with explicit labels based on action:
> 
> 1. "Speak Prompt" for speaking the prompt
> 2. "Speak Step N" for each given step
> 3. "Speak My Work" for the my work section denoting the current editable step
> 
> Along with the accompanying
> 
> 1. "Stop Speaking Prompt"
> 2. "Stop Speaking Step N"
> 3. "Stop Speaking My Work"

@alexrcabral 
Do we need the TTS button on the Math Editor for Problem Set Creator?
![image](https://user-images.githubusercontent.com/6897505/83553999-b8269580-a529-11ea-92ac-8fd65d73b409.png)

**Comment by alexrcabral** [comment] 2020-06-03 00:01
@rupeshparab Thanks for bringing this up. Yes, there should be TTS on the Math Editor for the Steps and the Math Editor for the Problem Set Creator, similar to how they're surfaced for problem solving. 

Labels: 
1. "Speak Problem N" / "Stop Speaking Problem N" for already created problems
2. "Speak Current Problem" / "Stop Speaking Current Problem" for the active problem in the Math Editor

**Comment by benetechMatt** [comment] 2020-07-01 22:13
Crossed out terms are read incorrectly. 

- No verbal indication the terms are crossed out
- duplicating operators such as - and +
- 1+13 is read as "plus plus one hundred and thirteen"

here is a video of the issue.  I used the tutorial example problem for testing
https://www.loom.com/share/bb68d58f706d4f488e6478067fc37755

**Comment by johnhbenetech** [comment] 2020-07-01 22:25
THanks @benetechMatt . Im gonna break this out into a separate issue. If there are other content-based oddities on how things are read (rather than if things are read) you can make a separate task to the Up Next column as they will likely require playing around in the mathlive land.

**Comment by bognasoldev89** [comment] 2020-07-02 09:56
Verified on qa env, Chrome v83.0.4103.116 and Firefox v77.0.1

1. 
> When there is a "clean up" row where crossed out items are removed, then only the second line with the removed elements should be read aloud.

At this moment both lines have TTS icon and both can be played independently. @alexrcabral @benetechMatt @johnhbenetech can you clarify, how it's supposed to work exactly?
![ms 995 1](https://user-images.githubusercontent.com/51324797/86339110-7fc2c600-bc53-11ea-9c40-299a33fa5743.png)

2. While I'm listening to the step and click "All problems" button (or next/previous problem, finish), it's not interrupted. Shouldn't it stop?

3. I added step, played it, and removed meanwhile. The reading was not interrupted. It works similarly for editing steps. What's the right behavior?

**Comment by rupeshparab** [comment] 2020-07-02 12:17
@johnhbenetech / @alexrcabral 
In this and the https://github.com/benetech/MathShare/issues/1268 issue, is the expected behavior that TTS Button should only be present on the first part of the step and that it will read the math from the second part (math after cleanup) and description of first part?

Also, in cases where a crossout mark is used but there is no cleanup step (user has not used the Calc button but has used crossout instead),, how should that be read?

**Comment by alexrcabral** [comment] 2020-07-02 16:23
> In this and the #1268 issue, is the expected behavior that TTS Button should only be present on the first part of the step and that it will read the math from the second part (math after cleanup) and description of first part?

@rupeshparab Yes, as @bognasoldev89 referenced the TTS button should be associated with steps, not lines. 

For example, the TTS button would be located after the words "Step 4", but not on the line underneath. When a user clicks the TTS button for Step 4, it would simply read out "7" from the cleanup line. 

> While I'm listening to the step and click "All problems" button (or next/previous problem, finish), it's not interrupted. Shouldn't it stop?
> 
> I added step, played it, and removed meanwhile. The reading was not interrupted. It works similarly for editing steps. What's the right behavior?

It should read out when the math it's reading is present. The correct behavior should be to stop playing when leaving the page, e.g. going to a different problem, back to all sets, or similarly navigating away to a point where the math is no longer present. It should continue playing during interactions on the math solve page (e.g. if you press the TTS button on Step 3 and type out another and press add step before it finishes).

**Comment by alexrcabral** [comment] 2020-07-02 16:28
> Also, in cases where a crossout mark is used but there is no cleanup step (user has not used the Calc button but has used crossout instead),, how should that be read?

I'm unclear what you mean here. Currently the cleanup step occurs on cross out, cross out & replace, and calculate. 

Screenshot from current QA: 

<img width="1031" alt="Mathshare QA problem solve page of 9 minus 9 minus 4x equals 4 minus 9. The following line has both minus 9s crossed out, followed by a cleanup step." src="https://user-images.githubusercontent.com/47576069/86385938-e93bd800-bc45-11ea-93ff-098d8ed7ad98.png">

In which case it reads out the cleaned up line, similar to calculate (in this case, negative 4x equals negative 5 on Step 3.

**Comment by rupeshparab** [comment] 2020-07-02 17:17
Got it, I thought that in case we don't use Calc button there won't be cleanup, but cleanup seems to be present for all cases with crossouts

**Comment by rupeshparab** [comment] 2020-07-02 17:49
I have pushed a fix for this

**Comment by alexrcabral** [comment] 2020-07-02 19:34
Got it. Thanks @rupeshparab!

**Comment by bognasoldev89** [comment] 2020-07-03 13:19
**Tested with success**

Verified on qa env
Verified on Chrome v83.0.4103.116 and Firefox v77.0.1

**Verified cases**
- playing TTS for each step
- stoping and running again TTS for each step
- changing page (previous/next problem, finish, all problems) while TTS for steps
- playing TTS for steps with cross-outs and clean-ups

**Summary**
In my opinion, TTS for each step seems to work properly now. Crossed out values are omitted and only clean-up parts are read. TTS is stopped while changing page.

**Closed by bognasoldev89** 2020-07-03 13:19 UTC
