### ISSUE TITLE
Enable 'Add Step' button, only when reason is provided

### ISSUE THREAD

**Issue by oskarhinc** [benetech/MathShare#177] opened 2018-06-21 10:08 UTC
The 'Add step' button could be disabled when reason is not provided, instead of displaying an alert. On disabled button hower, there should be info of why is it disabled and the "hand" mouse button should be replaced with a normal pointer od even something that indicates it's disabled.
After reason is provided, the button should be available immediately.
Notice that it might affect accessibility when a button is not clickable, so it should be discussed first.

![177](https://user-images.githubusercontent.com/19305104/41712856-dfb5ffec-754b-11e8-8e74-e702f0273f1a.png)

Additionally - consider improving default (on the screenshot) disabled button look - it's not clear that it's disabled on the first look.

**Comment by johnhbenetech** [comment] 2018-06-22 06:58
duplicate of #104, making this the main task.

@oskarhinc what do you think about moving away from the pop-up alert box and moving towards an error text model?

For example, as discussed in #104 the Add Step can always be active, but if it's clicked with a blank explanation, the explanation box become focused and alert text is displayed below the input box.

I would recommend some research into the role='alert' attribute that will be relevant for making this accessible:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

**Comment by oskarhinc** [comment] 2018-06-25 08:55
@johnhbenetech I think that might be a better idea.

**Comment by johnhbenetech** [comment] 2018-08-27 20:59
Closing this as we have solved with alerts

**Closed by johnhbenetech** 2018-08-27 20:59 UTC
