### ISSUE TITLE
Loading... Placeholder appears when opening a problem with blank last step

### ISSUE THREAD

**Issue by abaranowska1** [benetech/MathShare#1272] opened 2020-07-02 09:37 UTC
**Describe the bug**
Additional steps are added after click Save or Finish button.

**To Reproduce**
1. Go to the Problem Set 
2. Click on the Problem
3. Add step for example with some cross out 
4. Click Save button

**Expected behavior**
In my opinion, only 2 steps should be visible not 3

**Screenshots**
![Peek 2020-07-02 11-16](https://user-images.githubusercontent.com/61964176/86341297-6707df80-bc56-11ea-8a85-a81e422bca63.gif)

**Desktop:**
 - OS: Ubuntu 16.04
 - Browser Chrome 
 - Version 83.0.4103.116

**Additional context**
I noticed also similar issue with additional step during I want to delete "My work" field content and click Finish button. 
Empty step is added to the list of steps.  And "Loading..." is shown in the "My work" section 

![Peek 2020-07-02 09-10](https://user-images.githubusercontent.com/61964176/86341863-2361a580-bc57-11ea-8b76-af7cb95c1f10.gif)

**Comment by abaranowska1** [comment] 2020-07-02 09:42
@alexrcabral @johnhbenetech 
Question to the issue from "Additional context". Is is the expected behavior that after click TTS button we can hear spelled  "L O  A D I N G . . . " instead of the word Loading ?

**Comment by alexrcabral** [comment] 2020-07-02 17:03
Good catch! This isn’t just with cross out, this is with any problem where the content of the math editor differs from what’s in the final step. If the math in the my work section is edited, but ultimately the same as the step before it (eg delete something and retype it) it does not add the extra step.

Expected behavior: Work which is not intentionally added should not be added as a step. Any changes made should be retained within the My Work and step description box when saving or finishing, and any applicable cleanup should remain in the step previous (and retained as an "change" to the My Work section). 

The only exception to this is if the student is sending a view only version of the set, such as to turn in a homework assignment. In this scenario, work shown in the math editor *that is different from the final step added* should be displayed as a final step.

**Comment by alexrcabral** [comment] 2020-07-02 17:05
> Question to the issue from "Additional context". Is is the expected behavior that after click TTS button we can hear spelled "L O A D I N G . . . " instead of the word Loading ?

Do you have steps to replicate, or specific browser/OS? I don't hear either "Loading" or "L O A D I N G", only the description of the step and the math, which is expected.

**Comment by johnhbenetech** [comment] 2020-07-02 17:13
@alexrcabral this seems at odds with https://github.com/benetech/MathShare/issues/843

Can you confirm exactly which combination of the requirements from these tasks we want?

Currently we dont store the information thats ephemerally in the my work area in the database. I believe that's what you may be suggesting we do?

**Comment by abaranowska1** [comment] 2020-07-03 06:29
> > Question to the issue from "Additional context". Is is the expected behavior that after click TTS button we can hear spelled "L O A D I N G . . . " instead of the word Loading ?
> 
> Do you have steps to replicate, or specific browser/OS? I don't hear either "Loading" or "L O A D I N G", only the description of the step and the math, which is expected.

@alexrcabral 
Steps to replicate : 
1. Go to the Problem Set
2. Click on the Problem
3. Add a step 
4. Remove the content of the "My Work" field 
5. Click Finish button 
6. Open Problem once again 
7. Click TTS button in "My Work" section 

OS: Ubuntu 16.04
Browser Firefox
Version 78.0.1

I mean, if the expected result is that in the math section in "my work" we can only hear math and letters and not whole words

**Comment by johnhbenetech** [comment] 2020-07-03 13:47
Ok so there's several separate things happening in this that I will try to break apart:

1. There is a bug that occurs when you visit a problem where the last step's math is blank. The my work area displays 'Loading...' text which is probably just a coding mistake where it's meant to be a placeholder but since there isn't content to replace it just remains there. @rupeshparab This issue will cover fixing this.

2. When that 'Loading' text appears, in mathlive syntac it is a collection of variables instead of a word - as such it reads letter by letter. We will **not fix** this issue as it will be obviated by fixing the above.

3. There seems to be requirement bugs coming out of #843. @alexrcabral please split out a new task for any workflow changes for product scoping as currently we have developed to the spec in #843

**Comment by johnhbenetech** [comment] 2020-07-03 14:00
Also @alexrcabral in your new task please also consider the edge case in @abaranowska1 first example. For steps where cross out or calc is used, what should be used to determine if the last step is "the same" as the previous step (to determine if it should be added or not).

In that first example you can see that after a clean up, it doesn't compare to the cleaned-up state but rather the pre-cleaned up state.

**Comment by alexrcabral** [comment] 2020-07-07 00:50
Created separate issue #1284 to address this

#843 is an older issue from last year and doesn’t match current expectations. The driver behind #843 was preventing loss of work, the primary difference is only in how it’s saved. 

Your comments on #843 are accurate — the proposal there of adding as a step is not consistent with existing paradigms (e.g. if someone didn’t describe their work, do we still add it as a step? What if the teacher set descriptions as required?). These are addressed in #1284

**Comment by rupeshparab** [comment] 2020-07-07 16:40
I have pushed a fix for the placeholder issue and addition of duplicate step after using crossouts

Note: I have removed the Loading... placeholder from My Work, it will still be shown in steps

**Comment by bognasoldev89** [comment] 2020-07-08 13:42
**Tested with success**

**Environment**
- QA env
- Browsers
-- Chrome v83.0.4103.116
-- Firefox v78.0.1

**Verified cases**
- Finishing problem after clean-up step
- Saving problem after clean-up step

**Summary**
I haven't noticed Loading... placeholder in My Work and additional steps were not added in any case.

**Attachments**
Examples from Chrome:
![ms 1272](https://user-images.githubusercontent.com/51324797/86925172-c7a08c00-c130-11ea-8fe9-c2d0dbb6a4ee.gif)
![ms 1272 2](https://user-images.githubusercontent.com/51324797/86925179-c96a4f80-c130-11ea-87cd-044a6b27369b.gif)

**Closed by bognasoldev89** 2020-07-08 13:42 UTC
Labels: bug
