### ISSUE TITLE
Clearer wording on how to retrieve your work

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#1073] opened 2020-03-26 17:42 UTC

**Comment by benetechMatt** [comment] 2020-03-28 01:33
@alexrcabral you suggested telling users to bookmark their work whenever they save it. Can you elaborate on that

**Comment by benetechMatt** [comment] 2020-03-28 01:36
from #1064
@benetechMatt 
One idea is adding a "bookmark work" link

 @jscholes
How do you envisage this working? In a recent announcement, Apple indicated that web apps will not be allowed to store local data for longer than seven days:

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

So the best approach would probably be to tell users that MathShare will work with their browser's standard bookmarking/favourites system (obviously ensuring that such an assertion is technically true).

**Comment by alexrcabral** [comment] 2020-04-08 17:36
@benetechMatt I don't recall suggesting this. It's a plausible workaround for students trying to save the link without signing in, but I wouldn't recommend it as the standard messaging because there are aspects we can't control. 

E.g. if on a shared computer in a computer lab, bookmarks are often wiped, and the student will lose their work. 

We should still allow the option of saving the link, and center the messaging around this.

Sample copy: 
"Sign in to save your work: [Google Classroom, Microsoft Teams]
Otherwise, save this link to access your work later."

**Comment by benetechMatt** [comment] 2020-04-08 22:42
@alexrcabral What are your thoughts on a good location for this messaging. I'm thinking of users that will never sign in because their district does not allow it. These messages would only be displayed if the user is not signed in.

Here are two ideas

Only in the "share" modal
![mockup of "share my answers" modal. At the bottom, below the sharing instructions and buttons is a box of text with a light gray background. Text says "Sign in to save your work: [Google Classroom, Microsoft Teams] Otherwise, save this link to access your work later."](https://user-images.githubusercontent.com/49413678/78840021-5c271100-79bf-11ea-81e0-c287e90b0130.png)

Second idea is a bar above the universal navigation bar. The first version has buttons for google and microsoft sign in.  The second version has the text "sign in" as a link that will display the sign in modal.
![two mockups of the save your work bar above the universal navigation bar.  The first version has buttons along with the same text.  At the end is a text box with the URL and a copy link button.  The second mockup has the same text but does not include the google and microsoft sign in buttons](https://user-images.githubusercontent.com/49413678/78840267-e8393880-79bf-11ea-9f71-a0df77ba12ec.png)

**Comment by alexrcabral** [comment] 2020-04-10 00:06
Neither. 

1) This is also in the modal for sharing responses, which is less relevant for error-prevention in losing saved work than the unsaved work warning modal. I also recommend sticking to the copy I suggested. The text in the mockup is very dense & difficult to read, particularly because it's trying to offer multiple courses of action at the same time. 

2) It should be an alert at the top of the problem set, **not** above the universal nav bar. The purpose of the nav bar is to stay consistent across the site, not have new information added to it. The nav bar itself already has a call to sign in, and adding more is distracting and potentially conflicting information, which is easy to miss because it's separate from the focus of the page (the problem itself). I recommend having an alert above my steps but below the prompt: "Warning: you are not signed in. Save this link to return to your work later [link]" 

Updated mockups in process

**Comment by benetechMatt** [comment] 2020-04-10 21:30
Created issue #1131 to address the need for creators to add a key to the problems

**Comment by alexrcabral** [comment] 2020-04-16 21:51
Updated mockup: 
<img alt="Mockup of the existing Mathshare interface. Below the problem set title and above the problem set controls is a warning centered in the middle of the screen. Text reads, Warning: You are not signed in. Save this link to return to your problem set later. A link is available in a text box in the line below, with a button labelled Copy with matching icon." src="https://user-images.githubusercontent.com/47576069/79509081-acb9f200-7fef-11ea-9d40-249197f03bde.png">

The warning should be centered both horizontally as well as vertically  between problem set title and problem set controls.

Text is 14pt and reads: "Warning: You are not signed in. Save this link to return to your problem set later." 
The line below has a textbox which is interactive to either copy the text with keyboard controls (control-c) or the copy button immediately to the right. 

The word "Warning" is bold and in red (#CD4C1D).

**Comment by alexrcabral** [comment] 2020-04-17 21:48
Problem set controls will be updated in future mockups, this issue is set to go.

**Comment by benetechMatt** [comment] 2020-04-18 05:37
![image](https://user-images.githubusercontent.com/49413678/79629176-a40b0e00-810c-11ea-8e83-2b5d14e24847.png)

![image](https://user-images.githubusercontent.com/49413678/79629184-b4bb8400-810c-11ea-886b-c3369d069ab0.png)

**Comment by johnhbenetech** [comment] 2020-04-19 20:03
@benetechMatt the mockups are confusing with regards to which link should be shown on which views. my assumption is that

* If you are on the 'edit' view it should show the edit link
* if you are on the 'solve' view it should show the solve link

is that correct?

**Comment by benetechMatt** [comment] 2020-04-19 20:36
Correct John. /edit link when you are on the /edit page. /solve link when you are on the /solve page

________________________________

**Comment by alexrcabral** [comment] 2020-04-28 19:47
Minor copy update: "signed in" should be changed to "logged in" to be consistent with #1136

**Comment by rupeshparab** [comment] 2020-05-01 16:58
I have added only the warning and copy section in this change, will be working on the share modal and problem set controls in their individual tasks (https://github.com/benetech/MathShare/issues/1086, https://github.com/benetech/MathShare/issues/1129).

This is how the UI is looking after the current change:

/solve
![image](https://user-images.githubusercontent.com/6897505/80823770-d29fe300-8bfa-11ea-9fa3-3cac2315e9a1.png)

/edit
![image](https://user-images.githubusercontent.com/6897505/80823821-e8150d00-8bfa-11ea-8b61-d1a8f033479d.png)

**Comment by alexrcabral** [comment] 2020-05-15 20:21
Thanks @rupeshparab and @jscholes!

Since the associated pull request #1177 was approved I'll move this issue into QA

**Comment by bognasoldev89** [comment] 2020-05-18 09:53
Verified on qa env.

**Verified cases**
- copying a link to Problem set as a not signed in user
-- /edit link
-- /solve link
- pasting those links as a
-- not logged in user
-- logged in user, both teacher and student

**Summary**
The links send a user to the right problem set with the right answers (if provided).

I saw one issue though:
- I logged in in a new tab at the same browser
- I pasted the link 
Result:
- I was sent me to an empty problem set. The name was changed to "Untitled Problem set" and problems provided were not available. 

Could it be some cookie issue? See the screenshot below.
When I opened another browser in the incognito mode, logged in, and paste the link, the desired problem set was available.
cc: @johnhbenetech @rupeshparab @jscholes 

![1073 3](https://user-images.githubusercontent.com/51324797/82198302-63b1d200-98fc-11ea-97cc-dedb7f9e07e1.png)
Screenshot of the empty problem set, the name is "Untitled Problem set", no sharing links are available, no buttons with problems to solve are available.

![1073 empty problem set](https://user-images.githubusercontent.com/51324797/82199501-0dde2980-98fe-11ea-9d0b-534adc0f2062.gif)
Gif picturing reproducing issue steps - copying the link, logging in in a new tab and pasting copied URL.

**Attachments**
Below I put screenshots of problem set solve and edit views for not logged in users:
- /edit problem set page
![1073 1](https://user-images.githubusercontent.com/51324797/82198650-e3d83780-98fc-11ea-83b7-40878e01958d.png)

- /solve problem set page
![1073 2](https://user-images.githubusercontent.com/51324797/82198692-f18dbd00-98fc-11ea-8a3c-d3989d433dfd.png)

**Comment by rupeshparab** [comment] 2020-05-18 16:09
These 2 issues are not introduced by this feature, both are present on production too.
Will move this ticket to product input, so that tasks can be created if those issues need to be fixed.

Listing the 2 issues:
1) Any user (logged out as well as signed in) with a link of a solution or a problem set created by another logged in user can get access to it.
2) Share link can be created for empty problem sets. We can either disable the button or hide it till the user adds 1 problem, will need some accessibility input too over here.

**Comment by johnhbenetech** [comment] 2020-05-18 17:13
@rupeshparab I think point 2 is a different problem. @bognasoldev89 correct me if i'm wrong, Bogna actually created a problem set as an unauthenticated user containing one problem (you can see this in the screenshare). She then got the solve permalink and visited it. She then copied the solve link from the unauthenticated page.

With that link copied, she opened a new tab and logged in, then attempted to load the solve link. The link didnt resolve or load the one problem.

I cant however reproduce this on QA but I'll keep trying

**Comment by rupeshparab** [comment] 2020-05-18 17:40
@johnhbenetech got it now
this could have happened if the save api failed and the share link wasn't updated.
I am also not able to replicate this issue

**Comment by bognasoldev89** [comment] 2020-05-19 06:56
@johnhbenetech exactly.
@rupeshparab but I tried the same link on another browser incognito mode and it worked. That's why I asked if this could be some cookies issue.

I recreated my reproductions steps and now logged in user can see the problem set correctly from the link.

**Comment by rupeshparab** [comment] 2020-05-19 18:04
It shouldn't be a cookie issue, as cookie is only being used for storing session. Moving this back to QA as I am not able to replicate the issue.

**Comment by bognasoldev89** [comment] 2020-05-20 07:40
@rupeshparab @johnhbenetech I couldn't reproduce this issue anymore.
I retested this feature again and it works fine now, without any interruptions.

**Closed by bognasoldev89** 2020-05-20 07:40 UTC
