### ISSUE TITLE
TTS button for current equation

### ISSUE THREAD

**Issue by benetechMatt** [benetech/MathShare#997] opened 2020-02-27 16:56 UTC

**Comment by benetechMatt** [comment] 2020-03-03 16:39
![mockup of the current equation editor with the TTS button to the left of the heading "My Work"](https://user-images.githubusercontent.com/49413678/75797656-1aa9a300-5d3b-11ea-8f14-00fdbd023549.png)

**Comment by benetechMatt** [comment] 2020-03-03 16:39
TTS will read the current equation and the explanation assuming both are enabled via personalization settings

**Comment by jscholes** [comment] 2020-04-17 23:52
@benetechMatt and @alexrcabral - Are you waiting for any accessibility input from us on this one?  Or are we waiting to see it in action?

**Comment by alexrcabral** [comment] 2020-05-08 16:25
@jscholes Nope if nothing stands out to you this is good to go. Other related accessibility suggestions are incorporated via #1001

**Comment by benetechMatt** [comment] 2020-07-01 22:06
when adding a problem, the TTS button stays on the loading animation and does not read the equation or prompt.  added equations and prompts do work as expected. https://www.loom.com/share/329c6c9d44b1479bbd902645ed9291db

**Comment by johnhbenetech** [comment] 2020-07-01 22:19
@abaranowska1 @bognasoldev89 I'm moving this back to dev to address the bug @benetechMatt  found. Feel free to add any additional issues to this task though during testing.

**Comment by abaranowska1** [comment] 2020-07-02 06:50
@benetechMatt @johnhbenetech 
1. I met the same issue also on Problem Set Edit View. The TTS button stays on the loading animation and does not read equation or prompt in the situation when I add something to the " My work ", but I didn't delete the previous step.
![Peek 2020-07-02 08-35](https://user-images.githubusercontent.com/61964176/86325380-36b54680-bc40-11ea-8415-cf88088d83ff.gif)
 2. The second thing is that Error message is thrown when I want to delete what I added and leave only default value from the previous step 
![Selection_492](https://user-images.githubusercontent.com/61964176/86325538-7ed46900-bc40-11ea-98b5-239ab87e7965.png)
![Peek 2020-07-02 08-42](https://user-images.githubusercontent.com/61964176/86325541-7f6cff80-bc40-11ea-8ae0-9776fcb18a15.gif)

**Steps to reproduce 1 and 2 issue:**
- Log in to MathShare app 
- Go to the Problem Set and open one Problem 
- Try to edit values from "My work" for example add something 
- Click TTS button 

-Log in to MathShare app 
- Go to the Problem Set and open one Problem
- Try to add some values to "My work" 
- Click TTS button 
- Stop TTS button
- Delete values that you add, leave only values from the previous step
- Click TTS button

**Comment by rupeshparab** [comment] 2020-07-02 08:13
@abaranowska1 
I have deployed a fix for this

**Comment by abaranowska1** [comment] 2020-07-02 09:57
@rupeshparab @benetechMatt 
One more question, in my opinion, something is wrong with recognizing text from my work description 
Example :
Solve x is read as Solve x (correct)
Solve xx is read as Solve twenty ( ? )
Solve xxx is read as Solve thirty ( ? )
Solve xxxx is read as Solve four x ( ? )
Solve xxxxx is read as Solve xxxxx ( ? )
Solve IV is read as Solve four ( ? )

I'm not sure about this thing, sometimes it recognized roman numbers sometimes not, if it is a bug I can create a ticket for it.

**Comment by johnhbenetech** [comment] 2020-07-02 10:39
@abaranowska1 please break the Roman numeral into a new task (and put it into up next column). Then you can test the changes @rupeshparab made for the bug for this issue

**Closed by johnhbenetech** 2020-07-02 10:39 UTC

**Comment by abaranowska1** [comment] 2020-07-02 10:53
@johnhbenetech #1273 ticket for Roman Numeral.
@rupeshparab Thanks for the fix. Now it looks fine. I cannot reproduce issues from the previous comments. I didn't have a situation when TTS icon stays on the loading animation. 

**Verified on:**
- Google Chrome Version 83.0.4103.116
- Firefox Version 77.0.1
